spring:
  security:
    oauth2:
      client:
        registration:
          tado:
            client-id: tado-web-app
            client-secret: wZaRN7rpjn3FoNyF5IFuxg9uMzYJcvOoQ8QWiIqS3hfk6gLhVlG57j5YNoZL2Rtc
            authorization-grant-type: password
        provider:
          tado:
            token-uri: https://auth.tado.com/oauth/token